import Image from 'next/image'
import Head from 'next/head'
import style from '../styles/Sections.module.css';
import Carousel from "../../components/Carousel.js";
import Section1 from '../../components/Section1.js';
import Section2 from '../../components/Section2.js';
import Section3 from '../../components/Section3.js';
import { useState } from 'react';



export default function Home({ products }) {
  const [modal, setModal]= useState(false);
  const [visible, setVisible] = useState(4);
  const showMoreBook = ()=>{
    setVisible((prevValue)=> prevValue + 4);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.4/flowbite.min.css" rel="stylesheet" />      </Head>
      <main>
      <Carousel />
            <Section1 />
        <div className={style.bigCard} >
          <div className={style.titleCard}>
            <span>BOOKS GALLERY</span>
            <h1>Popular Books</h1>
            <hr />
          </div>
          <div className={style.cards}>
            {products.slice(0,visible).map((book) => (<Section2 key={book.id} book={book} modal={modal} setModal={setModal} />
            ))}
          </div>
        </div>
        <button className={style.LoadMore} onClick={showMoreBook}>Load More</button>

        <Section3 />
      </main>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.4/flowbite.min.js"></script>
    </>
  )
}
export async function getStaticProps() {
  const req = await fetch("https://example-data.draftbit.com/books");
  const products = await req.json();

  return {
    props: { products }
  };
}